# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 900000 #900000 #80000 #50000 #60000 
evaluation_epsilon: 0.0
runner: "episode"
# runner: "parallel"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 100
target_update_interval_or_tau: 100 
obs_agent_id: True
obs_last_action: True
obs_individual_obs: False
# learning rate
lr_reduce_interval: 100000
lr_step: 0.6

# use the Q_Learner to train
standardise_returns: False
standardise_rewards: True
agent_output_type: "q"
learner: "dtqn_learner"
double_q: True
vs_enabled: True

mixer: "tmix"
use_rnn: False
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
embed_dim: 512
out_channels: 512
t_dim: 512
ff: 2048
heads: 4
t_depth: 1
is_noise: False
name: "tmix"